remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-include-cache
- jekyll-archives
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: "/assets/images/mast-logo88.jpg"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      show_date: true
      breadcrumbs: true  # disabled by default
      permalink: /:categories/:title/
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
